### PR TITLE
Update JS SDK 10.18.0

### PR DESCRIPTION
**Pull request by NicoZelaya**
# React SDK

## Extra Notes

### CODE REVIEW

**Comment by NicoZelaya** [comment]
Leaving this PR here to be merged into development and included on the upcoming release. Made the cut to npm as a hotfix (branching from master) to avoid the attributes binding functionality from going out with it on rc.1

**Review by EmilianoSanchez — APPROVED** [review]
LGTM. Only a comment about the `unknown as` casting, it should be able to be removed.

**Review by EmilianoSanchez — APPROVED** [review]
LGTM

**Review by EmilianoSanchez — APPROVED** [review]
LGTM

**Pull request merged**
